# H2 Database 設定
spring:
  h2:
    console:
      enabled: true
      path: /h2-console/    # 不能取代正式的MYSQL等，雖是記憶體  
  datasource:
#    url: jdbc:h2:mem:mydb;   # H2 Database 在 RAM 裡執行. 停止服務就會消失.
    url: jdbc:h2:file:./src/main/resources/h2db/mydb2;    # H2 Database 儲存在檔案裡
    username: root
    passwd: 1234
    
